name: Test

on:
  pull_request:
    types: [opened]
  push:
    branches:
      - '**'
      - '!main'

jobs:
  test:
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 'latest'
      - uses: actions/setup-node@v4
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
